language: javascript
branches:
  only:
  - master
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- nvm install && nvm use
install:
- npm install
script:
- npm run prepush | tee 'prepush.log'
- npm run precommit
after_success:
- npm run update-coverage
after_script:
- yarn danger
env:
  global:
  - CODECLIMATE_API_HOST=https://codebeat.co/webhooks/code_coverage
  - secure: k4aZRKZDfC9vDUgkfs5CcbwTdGq5Sr9KL5DKnFiio2N3g6rj8cRE7OgW5byNAiw58eqSbpzf5NvGfzQhedVzkExMRdwflPr5dILAhx6r9N9PbJpTG4Bilom3zqKdz5RtM+0VYe5h6PhDBs4bqh7VT4Kc0oax5yTNC2tZOKmg1Jk6fqFQL8MQoYw46V2NzqGzLTMmO3GKbe+J+Ra10SGFWLbDmLqn28R2Bd8HLz22RwyFpcUGNfoufZ0AuFxJ4jYu5JMAOndRmsWp2yGUL8rRG0JSIcSFOKFTM7JMXRUxK//RHsI0oW0rsxqPVWNShZkIxuAIaRsW7F9Jo2UWPZx6UQN4k4QLu/7V0epKaInCSr1arV5/EhXsl3tOJIAANFx5XKpQAEMbKic7flQk/AHC4WNIb02eDJKqyp1WQip7CgA/tE+TkutCynJo+6tYaLnxboBaXu6Lo0Pxt3/1Vd10aCCzqGrqo4eA4V2OFucZz8O/mszox+e9m9FQCmYxtIQCOm4dweMl+Nq/qBIO91Mtm1oLjohnLmQP6M+hmO3NWz2lpmBwFne5tdwD0DuvycE9Q0ag5LKbrVGyqX6eeTC7u3I0MbqEeUCXblqzw1eWCygAe2BOWVzQ0v9rjtZIvPwNoLedjLvQJygr30nXNHo9ZbbIOKFBRYAtmVYus57Z95k=
  - secure: TRRr042OI8q0cHNrStKwRQ8H8Pl2U/o4nE16OWM+tGSdEnSilr/4RWz4VjJFSFoyr/IZorKUDBTVIduVl7CLFohxqp6bSlCBux2hmTeLWun+LXiNCVRxcEHzMdRXPS1NmiIU20lQ7Sm6yJOeDifM4MJ1KO7voJ0FMNpVnUSMZ3bgfMp3dJYq/KJuowA9/Yh6kM7hIOS1uq8wfZ289xU5u6vkXfHjoaQlOs+syt269bIrRcIVUgqB3piA9jM8jhBbxpPC5b7tq5HK0K+Kw4vIipOSw22YHcFurWQ6pKmUGvViIxhyFdovM770x/L9tqlmNjfh9llmEtRrF36UwB4AOTU9KCmZby283cqcbx8s1U7zpTSKFPcEG7QkfZz1qLuHJ0ALkl1pVBCP6vHA2XrkaFf6r36B/oquNDDbZpR7jQyNsfY36RzhpDTznqpGgZjl/Dq8dZoGBgMNf55dVu8pnMs13dyf2uBaVOtbHtk5akYbd/n/jXM7WMer3haabG3IIvQthqAhVlp2LpBtLxmNAuTcFcdyLjmAbZxwL2rMTJnyKJr+Fz86EgHpLL3Wyy2Vqkj3JwPNlY7pUWx1nB+EjvlsVHLDLtnNi6z/ZM9csrAmdKpNwEyZG4LNIc90yGiBGnJZY9esZ8GCycdU/s8UebkVOXxU5wfWr4ttpMySR+I=
